### ISSUE TITLE
Compatibility with 4.6/4.7?

### ISSUE THREAD

**Issue by MegaphoneJon** [cividesk/com.cividesk.sync.constantcontact#1]
Hi Nicolas,

I had a client asking about integration with Constant Contact; your info.xml says it works through 4.5, but I also see some recent commits.  I wanted to know if this has been tested in production with 4.6/4.7?  If not, how likely is it do you think it'll work?  As you know, I'm not above putting in a bit of work to get compatibility, but I thought I'd ask how much to expect.

**Comment by nganivet** [comment]
Works with 4.6, should work with 4.7 but untested.

Sent from my iPhone

On Mar 4, 2016, at 1:23 PM, Jon notifications@github.com wrote:

Hi Nicolas,

I had a client asking about integration with Constant Contact; your
info.xml says it works through 4.5, but I also see some recent commits. I
wanted to know if this has been tested in production with 4.6/4.7? If not,
how likely is it do you think it'll work? As you know, I'm not above
putting in a bit of work to get compatibility, but I thought I'd ask how
much to expect.

—
Reply to this email directly or view it on GitHub
https://github.com/cividesk/com.cividesk.sync.constantcontact/issues/1.

**Comment by MegaphoneJon** [comment]
Thanks!
