### ISSUE TITLE
CiviCRM 4.6.19 - Constant Contact Sync Id setting on group does not save

### ISSUE THREAD

**Issue by axon-obriend** [cividesk/com.cividesk.sync.constantcontact#4]
This extension does not list 4.6 or 4.7 support, but I thought I'd ask anyway.

I've installed the extension from GitHub here on 4.6.19. I've connected it with a brand new Constant Contact account. I've set up an API key and it seems to be talking to CC.

When I go into a CiviCRM group's settings, the picklist is populated with the lists that are set up in Constant Contact, and the list gets updated with changes in CC after I manually kick off the Constant Contact Sync scheduled job. When I select a list, and save the group and manually run the Constant Contact Sync schedule job, the log says, "No groups defined for synching." Editing the settings for the group again shows the Constant Contact Sync Id value was not saved and the record just displays -select-.

Any thoughts? I haven't used this extension before, so I'm not 100% sure it's not a configuration issue or something else I'm doing/not doing, but the extension configuration says "Successful" when saved and the fact that the lists are refreshed when the schedule job runs seems to indicate that it's authenticating properly.

**Comment by nganivet** [comment]
There's a bug in the setup screen on 4.6, but after you've overcome this (I store the setting directly in the database) the sync works perfectly.

**Comment by axon-obriend** [comment]
Thanks! Is that an easy fix? If you point me to the code I might be able to finagle a pull request.

**Comment by nganivet** [comment]
I think you can do this by unchecking the 'set by PHP program' (ie. read only) checkbox in the group custom fields ...

**Comment by axon-obriend** [comment]
Deselecting "View only?" did the trick. Thanks!
